import type { Metadata } from 'next'
import { Link } from '@/i18n/navigation'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'
import { AppleLogo } from '@/components/AppleLogo'
import { Check, ChevronRight, Hammer, Shield, FolderGit2, RotateCcw, Download } from 'lucide-react'

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'Mac Cleaner for Developers — Clear Xcode DerivedData, node_modules & Caches Safely',
    description:
      'Reclaim tens of gigabytes from Xcode DerivedData, node_modules, CocoaPods, Cargo target, Gradle and package caches. Project-aware, safe-to-rebuild labels, never touches source code or .git.',
    alternates: { canonical: '/developers' },
  }
}

const TARGETS = [
  { tool: 'Xcode', items: 'DerivedData, Archives, iOS/watchOS DeviceSupport, simulator caches', restore: 'Rebuilt on the next build or device connection' },
  { tool: 'JavaScript / Node', items: 'node_modules, .next build cache, npm, Yarn and pnpm caches', restore: '`npm install`, `yarn` or `pnpm install`' },
  { tool: 'Swift', items: '.build folders, Swift Package Manager cache, CocoaPods Pods and cache', restore: '`swift build`, `pod install`' },
  { tool: 'Rust', items: 'Cargo target folders and the registry cache', restore: '`cargo build`' },
  { tool: 'Python', items: 'Virtual environments (.venv, venv) and the pip cache', restore: 'Recreate with `python -m venv`, reinstall requirements' },
  { tool: 'Java / Gradle / Android', items: 'Gradle build output and the Gradle cache', restore: 'The next Gradle build' },
  { tool: 'Homebrew & Go', items: 'Homebrew downloads and the Go build cache', restore: 'Fetched again on demand' },
]

const SAFETY = [
  { icon: FolderGit2, title: 'Project-aware, not path-guessing', text: 'A node_modules, target or build folder is only listed when its manifest (package.json, Cargo.toml, Podfile, build.gradle…) sits right next to it. Source code and .git folders are never candidates.' },
  { icon: Shield, title: '"Safe to rebuild" vs "Review first"', text: 'Anything from a project you touched in the last two weeks, Xcode archives you may have shipped, and DerivedData while Xcode is open are labelled Review first and left unselected.' },
  { icon: RotateCcw, title: 'Trash first, always', text: 'Everything is moved to the Trash rather than erased, so you can put it back. Your tools regenerate the rest automatically.' },
  { icon: Hammer, title: 'Fast and local', text: 'Scanning a home folder with hundreds of projects typically takes well under a minute, entirely on your Mac. No file names or paths are uploaded.' },
]

const FAQS = [
  { q: 'Is it safe to delete node_modules?', a: 'Yes. node_modules is fully regenerated by npm, Yarn or pnpm from your lockfile. MacDiskCleaner only lists it when a package.json sits next to it, marks recently used projects as Review first, and moves it to the Trash so it stays recoverable.' },
  { q: 'Can I delete Xcode DerivedData?', a: 'Yes. DerivedData holds build products and indexes that Xcode recreates. The first build afterwards is slower. Quit Xcode first — MacDiskCleaner warns you if it is running.' },
  { q: 'Should I delete Xcode Archives?', a: 'Only ones you no longer need. Archives are what you need to re-symbolicate crash logs for builds you shipped, so MacDiskCleaner labels them Review first and never pre-selects them.' },
  { q: 'Will it touch my source code or git history?', a: 'No. It only targets dependency folders, build output and tool caches, each verified against a sibling manifest file. .git folders and source files are never candidates.' },
  { q: 'How much space can developers recover?', a: 'It depends on how many projects you keep around, but 20–100+ GB is common: a single Node project can hold 1 GB of node_modules, and Gradle, npm and Xcode caches add tens of gigabytes more.' },
  { q: 'Is the Developer tab free?', a: 'Scanning is always free. Like every cleanup, it counts toward the 2 GB free allowance; Pro ($12.99 one-time) removes the limit.' },
]

export default async function DevelopersPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQS.map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })),
  }
  return (
    <>
      <Navbar />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <main className="min-h-screen bg-white">
        <section className="pt-32 pb-20 px-6">
          <div className="max-w-[820px] mx-auto text-center">
            <div className="flex items-center justify-center gap-1.5 text-[13px] text-[#6E6E73] mb-8">
              <Link href="/" className="hover:text-[#1D1D1F]">MacDiskCleaner</Link>
              <ChevronRight size={13} />
              <span>For developers</span>
            </div>
            <h1 className="text-[36px] sm:text-[46px] md:text-[60px] font-extrabold tracking-[-0.03em] leading-[1.05] text-[#1D1D1F] mb-6">
              Take back your disk from <span className="text-[#007AFF]">build junk.</span>
            </h1>
            <p className="text-[19px] text-[#6E6E73] leading-relaxed max-w-[640px] mx-auto mb-10">
              Xcode, Node, Gradle and friends quietly fill a Mac with gigabytes of regenerable files. The Developer tab finds them, tells you which are safe to rebuild, and moves them to the Trash — without ever touching your source code.
            </p>
            <a href="/downloads/MacDiskCleaner.dmg" className="btn-primary text-[16px] py-[14px] px-8 inline-flex">
              <AppleLogo size={16} /> Download Free for Mac <Download size={16} />
            </a>
          </div>
        </section>

        <section className="py-20 bg-[#F5F5F7] px-6">
          <div className="max-w-[900px] mx-auto">
            <h2 className="text-[28px] font-extrabold tracking-tight text-[#1D1D1F] mb-3 text-center">What it finds</h2>
            <p className="text-[15px] text-[#6E6E73] text-center mb-10 max-w-[520px] mx-auto">Seven toolchains, every artifact your tools rebuild on their own.</p>
            <div className="bento-card overflow-hidden">
              {TARGETS.map((t) => (
                <div key={t.tool} className="grid grid-cols-1 md:grid-cols-[180px_1fr_1fr] gap-2 md:gap-6 px-6 py-5 border-b border-[rgba(0,0,0,0.06)] last:border-0">
                  <p className="text-[15px] font-bold text-[#1D1D1F]">{t.tool}</p>
                  <p className="text-[14px] text-[#1D1D1F]">{t.items}</p>
                  <p className="text-[14px] text-[#6E6E73]">{t.restore}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="py-20 px-6">
          <div className="max-w-[900px] mx-auto">
            <h2 className="text-[28px] font-extrabold tracking-tight text-[#1D1D1F] mb-10 text-center">Built so you never lose work</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {SAFETY.map((s) => (
                <div key={s.title} className="bento-card p-7">
                  <div className="w-10 h-10 rounded-xl bg-[#007AFF]/10 flex items-center justify-center mb-4">
                    <s.icon size={19} className="text-[#007AFF]" />
                  </div>
                  <p className="text-[16px] font-bold text-[#1D1D1F] mb-2">{s.title}</p>
                  <p className="text-[14px] text-[#6E6E73] leading-relaxed">{s.text}</p>
                </div>
              ))}
            </div>
            <p className="text-center mt-8 text-[14px]">
              <Link href="/security" className="font-semibold text-[#007AFF] inline-flex items-center gap-1">
                How MacDiskCleaner keeps your files safe <ChevronRight size={14} />
              </Link>
            </p>
          </div>
        </section>

        <section className="py-20 bg-[#F5F5F7] px-6">
          <div className="max-w-[560px] mx-auto">
            <h2 className="text-[22px] font-bold text-[#1D1D1F] mb-6 text-center">Free to scan, fair to keep</h2>
            <ul className="space-y-3 bento-card p-8">
              {['Scan everything — always free', 'Clean up to 2 GB free, lifetime', 'Pro: $12.99 once removes the limit, no subscription', 'Universal app: Apple Silicon and Intel'].map((r) => (
                <li key={r} className="flex items-start gap-3 text-[15px] text-[#1D1D1F]">
                  <Check size={16} className="text-[#34C759] flex-shrink-0 mt-0.5" strokeWidth={2.5} /> {r}
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section className="py-24 px-6">
          <div className="max-w-[720px] mx-auto">
            <h2 className="text-[32px] font-extrabold tracking-tight text-[#1D1D1F] mb-10 text-center">Frequently asked</h2>
            <div className="divide-y divide-[rgba(0,0,0,0.06)]">
              {FAQS.map((f) => (
                <details key={f.q} className="group py-5 cursor-pointer">
                  <summary className="flex justify-between items-center text-[16px] font-semibold text-[#1D1D1F] list-none">
                    {f.q}
                    <ChevronRight size={17} className="text-[#6E6E73] transition-transform group-open:rotate-90" />
                  </summary>
                  <p className="mt-3 text-[15px] text-[#6E6E73] leading-relaxed">{f.a}</p>
                </details>
              ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
